apiVersion: app/v1
kind: ReplicaSet
metadata:
 name: nginx-rs
# labels:
  #  app: nginx
  #  tier: frontend 
spec:
 # modify replicas according to your case
 replicas: 3  #1
 selector:   # replica-set labels #2
  matchLabels:
   app: nginx
   tier: frontend
 template: # pod-definition  #3
  metadata:
   labels:
      app: nginx
      tier: frontend
  spec:
   containers:
    - name: nginx
      image: nginx:mainline-alpine3.18-perl 
  

   