apiVersion: v1
kind: Pod
metadata:
 name: multi-container
 #namespace: roboshop
spec: 
  # list of containers
   containers: 
    - name: nginx   #container -1
      image: nginx
      ports: 
       -containerPort: 80
    - name: almalinux   #container -2
      image: almalinux:8
      command: ["sleep", "300"]
