apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
spec:
  # list of containers
  containers:
  - name: hello-pod
    image: nginx
    #here with this line port will not be opened, just for information
    ports:
    - containerPort: 80
    resources:

      requests:                 #soft limit
        cpu: "100m" # Request 100 milliCPU (0.1 CPU core)   (m for microns)
        memory: "68Mi"  # Request 68 megabytes of memory      (MB means Mi here)

      limits:                    #hard limit
        cpu: "200m"
        memory: "128Mi"


#1000m = 1 cpu    
#250m = 0.25 cpu
